TEMPLATEROOT = ..

# object files

OBJS  =  $(STARTUP) main.o syscalls.o uart.o
OBJS +=  stm32f10x_gpio.o stm32f10x_rcc.o stm32f10x_usart.o 

# include common make file

include $(TEMPLATEROOT)/Makefile.common
