TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g
ASFLAGS = -g

# object files

OBJS  =  $(STARTUP) main.o uart.o xprintf.o ultrasonic.o
OBJS +=  stm32f10x_gpio.o stm32f10x_rcc.o stm32f10x_tim.o stm32f10x_usart.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


