TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g
ASFLAGS = -g

# object files

OBJS  =  $(STARTUP) main.o
OBJS +=  stm32f10x_gpio.o stm32f10x_rcc.o stm32f10x_adc.o stm32f10x_tim.o misc.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common
